### ISSUE TITLE
Your validator doesn't work as published. Instructions needed.

### ISSUE THREAD

**Issue by 88kbbq** [dorightdigital/amp-validator#2]
Following your demo:
amp-validator http://pos.88k.com.tw
Returns:
/usr/bin/env: node: No such file or directory
How are we supposed to use this app?

**Comment by nataliecarey** [comment]
Hi, which platform are you on?  Can you try running another globally installable node tool like:

`npm install -g grunt-cli && grunt`
and/or
`npm install -g bower && bower`
then
`npm install -g amp-validator && amp-validator http://pos.88k.com.tw`

And see if they work?  It looks like the problem is with the pathing of node on your machine.  If you can run `bower` & `grunt` but not `amp-validator` then there's obviously something different/wrong about the way I'm installing globally.

For me it gets the output I'd expect (as the link you've provided isn't AMP):

```
amp-validator http://pos.88k.com.tw

http://pos.88k.com.tw failed validation
 -- Doesn't seem to be an AMP page
```

**Comment by 88kbbq** [comment]
So my AMP HTML pages validate in Chrome but not with your amp-validator. Install on Mac X El Capitan Nodejs stable. On install via npm, I see this output:

`gyp ERR! build error 
gyp ERR! stack Error:`make`failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/home/node_modules/utf-8-validate
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install:`node-gyp rebuild`
npm WARN install:utf-8-validate@1.2.1 Exit status 1
/Users/home
└─┬ amp-validator@0.1.3 
  ├── bluebird@3.1.2 
  ├── colors@1.1.2 
  ├─┬ commander@2.9.0 
  │ └── graceful-readlink@1.0.1 
  ├── format-json@1.0.3 
  ├── lodash@3.10.1 
  └─┬ zombie@4.2.1 
    ├─┬ babel-runtime@5.8.29 
    │ └── core-js@1.2.6 
    ├── debug@2.2.0 
    ├─┬ eventsource@0.1.6 
    │ └─┬ original@1.0.0 
    │   └─┬ url-parse@1.0.5 
    │     ├── querystringify@0.0.3 
    │     └── requires-port@1.0.0 
    ├── iconv-lite@0.4.13 
    ├─┬ jsdom@5.3.0 
    │ ├── acorn@1.2.2 
    │ ├─┬ acorn-globals@1.0.9 
    │ │ └── acorn@2.7.0 
    │ ├── browser-request@0.3.3 
    │ ├── cssom@0.3.0 
    │ ├── cssstyle@0.2.31 
    │ ├─┬ escodegen@1.8.0 
    │ │ ├── esprima@2.7.1 
    │ │ ├── estraverse@1.9.3 
    │ │ ├── esutils@2.0.2 
    │ │ ├─┬ optionator@0.8.1 
    │ │ │ ├── deep-is@0.1.3 
    │ │ │ ├── fast-levenshtein@1.1.0 
    │ │ │ ├── levn@0.3.0 
    │ │ │ ├── prelude-ls@1.1.2 
    │ │ │ ├── type-check@0.3.2 
    │ │ │ └── wordwrap@1.0.0 
    │ │ └─┬ source-map@0.2.0 
    │ │   └── amdefine@1.0.0 
    │ ├─┬ htmlparser2@3.9.0 
    │ │ ├── domelementtype@1.3.0 
    │ │ ├── domhandler@2.3.0 
    │ │ ├─┬ domutils@1.5.1 
    │ │ │ └─┬ dom-serializer@0.1.0 
    │ │ │   └── domelementtype@1.1.3 
    │ │ ├── entities@1.1.1 
    │ │ └─┬ readable-stream@2.0.5 
    │ │   ├── core-util-is@1.0.2 
    │ │   ├── inherits@2.0.1 
    │ │   ├── isarray@0.0.1 
    │ │   ├── process-nextick-args@1.0.6 
    │ │   ├── string_decoder@0.10.31 
    │ │   └── util-deprecate@1.0.2 
    │ ├── nwmatcher@1.3.7 
    │ ├── parse5@1.5.1 
    │ ├─┬ tough-cookie@0.13.0 
    │ │ └── punycode@1.4.0 
    │ ├── xml-name-validator@2.0.1 
    │ └── xmlhttprequest@1.8.0 
    ├── mime@1.3.4 
    ├── ms@0.7.1 
    ├─┬ request@2.67.0 
    │ ├── aws-sign2@0.6.0 
    │ ├── bl@1.0.1 
    │ ├── caseless@0.11.0 
    │ ├─┬ combined-stream@1.0.5 
    │ │ └── delayed-stream@1.0.0 
    │ ├── extend@3.0.0 
    │ ├── forever-agent@0.6.1 
    │ ├─┬ form-data@1.0.0-rc3 
    │ │ └── async@1.5.2 
    │ ├─┬ har-validator@2.0.6 
    │ │ ├─┬ chalk@1.1.1 
    │ │ │ ├── ansi-styles@2.1.0 
    │ │ │ ├── escape-string-regexp@1.0.4 
    │ │ │ ├─┬ has-ansi@2.0.0 
    │ │ │ │ └── ansi-regex@2.0.0 
    │ │ │ ├── strip-ansi@3.0.0 
    │ │ │ └── supports-color@2.0.0 
    │ │ ├─┬ is-my-json-valid@2.12.4 
    │ │ │ ├── generate-function@2.0.0 
    │ │ │ ├─┬ generate-object-property@1.2.0 
    │ │ │ │ └── is-property@1.0.2 
    │ │ │ ├── jsonpointer@2.0.0 
    │ │ │ └── xtend@4.0.1 
    │ │ └─┬ pinkie-promise@2.0.0 
    │ │   └── pinkie@2.0.1 
    │ ├─┬ hawk@3.1.3 
    │ │ ├── boom@2.10.1 
    │ │ ├── cryptiles@2.0.5 
    │ │ ├── hoek@2.16.3 
    │ │ └── sntp@1.0.9 
    │ ├─┬ http-signature@1.1.0 
    │ │ ├── assert-plus@0.1.5 
    │ │ ├─┬ jsprim@1.2.2 
    │ │ │ ├── extsprintf@1.0.2 
    │ │ │ ├── json-schema@0.2.2 
    │ │ │ └── verror@1.3.6 
    │ │ └─┬ sshpk@1.7.3 
    │ │   ├── asn1@0.2.3 
    │ │   ├── assert-plus@0.2.0 
    │ │   ├─┬ dashdash@1.12.2 
    │ │   │ └── assert-plus@0.2.0 
    │ │   ├── ecc-jsbn@0.1.1 
    │ │   ├── jodid25519@1.0.2 
    │ │   ├── jsbn@0.1.0 
    │ │   └── tweetnacl@0.13.3 
    │ ├── is-typedarray@1.0.0 
    │ ├── isstream@0.1.2 
    │ ├── json-stringify-safe@5.0.1 
    │ ├─┬ mime-types@2.1.9 
    │ │ └── mime-db@1.21.0 
    │ ├── node-uuid@1.4.7 
    │ ├── oauth-sign@0.8.0 
    │ ├── qs@5.2.0 
    │ ├── stringstream@0.0.5 
    │ └── tunnel-agent@0.4.2 
    ├── tough-cookie@2.2.1 
    └─┬ ws@0.8.1 
      ├── options@0.0.6 
      └── ultron@1.0.2 

npm WARN ENOENT ENOENT: no such file or directory, open '/Users/home/package.json'
npm WARN EPACKAGEJSON home No description
npm WARN EPACKAGEJSON home No repository field.
npm WARN EPACKAGEJSON home No README data
npm WARN EPACKAGEJSON home No license field.`

**Comment by nataliecarey** [comment]
@88kbbq, can you update and try again please?  `npm update -g amp-validator` - the new version is 0.1.4 and it solved these problems for me.
